version: '3.7'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - db-network
    environment:
      HOST: db
      USER: root
      PASSWORD: password
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
      - ./data/crypto-tracker-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crypto-tracker
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db-network
networks:
  db-network: